name: Html lint for Develop

on:
  push:
    branches: [release]


jobs:
  html-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install HTML Lint
        run: npm install htmlhint
    
      - name: Lint files run
        run: npx htmlhint "src/**/*.html" 

      

      