name: Style lint for Develop

on:
  push:
    branches: [release]



jobs: 
  style-lint: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Style Lint
        run: npm install stylelint

      - name: Lint files run
        run: npx stylelint "styles/**/*.css"